import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const root=new URL('../../',import.meta.url).pathname.replace(/^\/(\w:)/,'$1');
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}'); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated;`);
for(const f of fs.readdirSync(root+'supabase/migrations').sort()) await db.exec(fs.readFileSync(root+'supabase/migrations/'+f,'utf8'));
const ids=[1,2,3,4,5,6].map(n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`);
for(const id of ids) await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[id,{full_name:'Test user',role:'admin'}]);
assert.equal((await db.query('select role from profiles where user_id=$1',[ids[0]])).rows[0].role,'senior');
await db.query("update profiles set role='coordinator' where user_id in ($1,$2)",[ids[3],ids[4]]);
await db.query("update profiles set role='admin' where user_id=$1",[ids[5]]);
const asUser=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
await asUser(ids[5]);
const cat=(await db.query("select save_category($1) id",[{name:'Wellness',description:'Wellness',is_active:true}])).rows[0].id;
const payload={category_id:cat,coordinator_id:ids[3],title:'Test activity',description:'A real description',venue:'Hall',start_at:new Date(Date.now()+86400000*2).toISOString(),end_at:new Date(Date.now()+86400000*3).toISOString(),cutoff_at:new Date(Date.now()+86400000).toISOString(),capacity:1,status:'open'};
await asUser(ids[3]);const a=(await db.query('select save_activity($1) id',[payload])).rows[0].id;
await asUser(ids[4]);await assert.rejects(db.query('select save_activity($1,$2)',[payload,a]),/Not authorized/);await assert.rejects(db.query('select * from participant_list($1)',[a]),/Not authorized/);
await asUser(ids[0]);
await assert.rejects(db.query("update profiles set role='admin' where user_id=$1",[ids[0]]),/permission denied/);
await assert.rejects(db.query('select save_activity($1)',[payload]),/Not authorized/);
let e=(await db.query('select * from enroll_in_activity($1)',[a])).rows[0];assert.equal(e.status,'confirmed');
await assert.rejects(db.query('select * from enroll_in_activity($1)',[a]),/already joined/);
await asUser(ids[1]);const w=(await db.query('select * from enroll_in_activity($1)',[a])).rows[0];assert.equal(w.status,'waitlisted');assert.equal((await db.query('select * from enrollments')).rows.length,1);
await asUser(ids[0]);await db.query('select withdraw_enrollment($1)',[e.enrollment_id]);
await asUser(ids[1]);assert.equal((await db.query('select * from enrollments')).rows[0].status,'confirmed');
await assert.rejects(db.query('select submit_feedback($1,5)',[w.enrollment_id]),/completed/);
await asUser(ids[3]);await assert.rejects(db.query('select record_attendance($1,true)',[w.enrollment_id]),/not available/);
await db.exec('reset role');await db.query("update activities set start_at=now()-interval '2 hours',end_at=now()-interval '1 hour',cutoff_at=now()-interval '3 hours',status='ongoing' where activity_id=$1",[a]);
await asUser(ids[4]);await assert.rejects(db.query('select record_attendance($1,true)',[w.enrollment_id]),/Not authorized/);
await asUser(ids[3]);await db.query('select record_attendance($1,true)',[w.enrollment_id]);
const finish={...payload,start_at:new Date(Date.now()-7200000).toISOString(),end_at:new Date(Date.now()-3600000).toISOString(),cutoff_at:new Date(Date.now()-10800000).toISOString(),status:'completed'};
await db.query('select save_activity($1,$2)',[finish,a]);
await asUser(ids[1]);await db.query('select submit_feedback($1,5,$2)',[w.enrollment_id,'Enjoyed this']);await assert.rejects(db.query('select submit_feedback($1,4)',[w.enrollment_id]),/unique/);
await db.query('select update_own_profile($1)',[{full_name:'Updated name',birthdate:null,role:'admin'}]);assert.equal((await db.query('select role from profiles where user_id=$1',[ids[1]])).rows[0].role,'senior');
await asUser(ids[3]);await assert.rejects(db.query('select save_announcement($1)',[{title:'Global',message:'Message',activity_id:null}]),/Not authorized/);
await db.query('select save_announcement($1)',[{title:'Local',message:'Message',activity_id:a}]);
await asUser(ids[5]);await db.query('select manage_user($1,$2,$3)',[ids[2],{role:'senior',account_status:'active',verification_status:'verified'},'Verified in person']);
assert.ok((await db.query('select * from audit_logs')).rows.length>=5);
await db.exec('reset role'); await db.exec('update settings set require_verification=true');
await asUser(ids[3]);const b=(await db.query('select save_activity($1) id',[payload])).rows[0].id;
await asUser(ids[0]);await assert.rejects(db.query('select enroll_in_activity($1)',[b]),/verification/);
await asUser(ids[2]);await db.query('select enroll_in_activity($1)',[b]);
await db.exec('reset role');await db.query("update activities set cutoff_at=now()-interval '1 minute' where activity_id=$1",[b]);
await asUser(ids[2]);await assert.rejects(db.query('select enroll_in_activity($1)',[b]),/Registration is closed/);
await db.exec('reset role');await db.exec('update settings set require_verification=false');
await asUser(ids[3]);const c=(await db.query('select save_activity($1) id',[payload])).rows[0].id;
await db.query('select manage_enrollment($1,$2,$3,$4)',[c,ids[0],'confirmed','Authorized walk-in']);
await assert.rejects(db.query('select manage_enrollment($1,$2,$3,$4)',[c,ids[1],'confirmed','Authorized walk-in']),/full/);
await db.query('select manage_enrollment($1,$2,$3,$4)',[c,ids[1],'waitlisted','Requested waitlist']);
await assert.rejects(db.query('select manage_enrollment($1,$2,$3,$4)',[c,ids[0],'cancelled','']),/reason/);
await db.query('select manage_enrollment($1,$2,$3,$4)',[c,ids[0],'cancelled','Participant withdrew']);
assert.equal((await db.query('select * from participant_list($1)',[c])).rows.find(e=>e.senior_id===ids[1]).status,'confirmed');
await asUser(ids[4]);await assert.rejects(db.query('select manage_enrollment($1,$2,$3,$4)',[c,ids[1],'cancelled','Wrong coordinator']),/Not authorized/);
await asUser(ids[0]);await assert.rejects(db.query('select promote_waitlist($1)',[c]),/permission denied/);
console.log('PASS: all migrations, safe provisioning, staff ownership, category/activity CRUD, capacity, duplicates, waitlists, RLS, attendance, feedback eligibility/uniqueness, profile safety, announcements, verification, audit, cutoff, staff walk-ins and capacity/cancellation, private helper permissions.');
await asUser(ids[3]);
const d=(await db.query('select save_activity($1) id',[payload])).rows[0].id;
await asUser(ids[0]);await db.query('select enroll_in_activity($1)',[d]);
await asUser(ids[1]);await db.query('select enroll_in_activity($1)',[d]);
await asUser(ids[3]);await db.query('select save_activity($1,$2)',[{...payload,capacity:2},d]);
assert.equal((await db.query('select * from participant_list($1)',[d])).rows.find(e=>e.senior_id===ids[1]).status,'confirmed');
await asUser(ids[2]);
assert.equal((await db.query('select * from enroll_in_activity($1)',[d])).rows[0].status,'waitlisted');
console.log('PASS: capacity increase promotes existing eligible waitlist before a newer registration.');

await db.exec('reset role');
await db.exec('update settings set require_verification=false');
await asUser(ids[3]);
const paidActivity=(await db.query('select save_activity($1) id',[{...payload,title:'Cash activity',is_free:false,fee:75}])).rows[0].id;
await asUser(ids[0]);
const paidEnrollment=(await db.query('select * from enroll_in_activity($1)',[paidActivity])).rows[0];
assert.equal(paidEnrollment.payment_status,'unpaid');
await db.exec('reset role');
await db.query("update activities set start_at=now()-interval '2 hours',end_at=now()+interval '1 hour',cutoff_at=now()-interval '3 hours',status='ongoing' where activity_id=$1",[paidActivity]);
await asUser(ids[3]);
await assert.rejects(db.query('select record_attendance($1,true)',[paidEnrollment.enrollment_id]),/Cash payment must be recorded/);
await db.query('select record_cash_payment($1,true,$2)',[paidEnrollment.enrollment_id,'Cash received by coordinator']);
assert.equal((await db.query('select payment_status from enrollments where enrollment_id=$1',[paidEnrollment.enrollment_id])).rows[0].payment_status,'paid');
await db.query('select record_attendance($1,true)',[paidEnrollment.enrollment_id]);
await db.exec('reset role');
assert.equal((await db.query("select details->>'method' method from audit_logs where action_type='payment.cash_recorded' order by created_at desc limit 1")).rows[0].method,'cash');
console.log('PASS: cash-only payments, unpaid attendance block, paid attendance, and payment audit.');
await db.close();
