import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}'); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated;`);
const root=new URL('../migrations/', import.meta.url);
for(const name of fs.readdirSync(root).sort()) await db.exec(fs.readFileSync(new URL(name, root),'utf8'));
const seed=fs.readFileSync('supabase/sample-data.sql','utf8');
await assert.rejects(db.exec(seed),/Set coordinator_uuid/);await db.exec('rollback');
const ids=[1,2,3].map(n=>`00000000-0000-4000-8000-00000000000${n}`);
for(const id of ids) await db.query('insert into auth.users(id) values($1)',[id]);
const admin=fs.readFileSync('supabase/first-admin.sql','utf8').replace('account_uuid uuid := null',`account_uuid uuid := '${ids[0]}'`);
await db.exec(admin);await db.exec(admin);
assert.equal((await db.query("select count(*)::int n from audit_logs where action_type='setup.admin_provisioned'")).rows[0].n,1);
await db.exec(seed);await db.exec(seed);
assert.equal((await db.query('select count(*)::int n from activities')).rows[0].n,8);
assert.equal((await db.query('select count(*)::int n from announcements')).rows[0].n,4);
assert.equal((await db.query('select count(*)::int n from categories')).rows[0].n,5);
await db.exec("update auth.users set email='senior1@example.com' where id='00000000-0000-4000-8000-000000000002'; update auth.users set email='senior2@example.com' where id='00000000-0000-4000-8000-000000000003';");
const withSeniors=fs.readFileSync('supabase/senior-workflows.sql','utf8');await db.exec(withSeniors);await db.exec(withSeniors);
assert.equal((await db.query('select count(*)::int n from enrollments')).rows[0].n,3);
assert.equal((await db.query('select count(*)::int n from attendance')).rows[0].n,1);
assert.equal((await db.query('select count(*)::int n from feedback')).rows[0].n,1);
assert.equal((await db.query("select count(*)::int n from enrollments where status='waitlisted'")).rows[0].n,1);
console.log('PASS: missing-account safeguard; admin bootstrap and repeat safety; 5 categories, 8 activities, 4 announcements; optional 3 enrollments, attendance, feedback; seed reruns without duplicates.');
await db.close();
