@extends('layout')
@section('title','Activity editor')
@section('content')
<a href="/workspace" class="back-link">← Back to workspace</a><h1>{{ $activity ? 'Edit activity' : 'Plan a new activity' }}</h1><p class="intro">Give participants clear information about what to expect.</p>
<form class="panel form-grid" method="post" action="{{ $activity ? '/workspace/'.$activity['activity_id'].'/edit' : '/workspace/create' }}">@csrf
<div class="wide"><label for="title">Activity title</label><input id="title" class="form-control" name="title" required maxlength="160" value="{{ old('title',$activity['title']??'') }}"></div>
<div class="wide"><label for="description">Description</label><textarea id="description" class="form-control" name="description" required maxlength="5000" rows="4">{{ old('description',$activity['description']??'') }}</textarea></div>
<div><label for="category_id">Category</label><select id="category_id" class="form-select" name="category_id" required>@foreach($categories as $c)@if($c['is_active'])<option value="{{ $c['category_id'] }}" @selected(old('category_id',$activity['category_id']??'')===$c['category_id'])>{{ $c['name'] }}</option>@endif @endforeach</select></div>
<div><label for="venue">Venue</label><input id="venue" class="form-control" name="venue" required maxlength="200" value="{{ old('venue',$activity['venue']??'') }}"></div>
@foreach(['start_at'=>'Starts','end_at'=>'Ends','cutoff_at'=>'Registration cutoff'] as $field=>$label)<div><label for="{{ $field }}">{{ $label }} (Philippine time)</label><input class="form-control" id="{{ $field }}" type="datetime-local" name="{{ $field }}" required value="{{ old($field,isset($activity[$field])?\Carbon\Carbon::parse($activity[$field])->timezone(config('app.timezone'))->timezone(config('app.timezone'))->format('Y-m-d\TH:i'):'') }}"></div>@endforeach
<div><label for="capacity">Capacity</label><input id="capacity" class="form-control" type="number" name="capacity" min="1" max="10000" required value="{{ old('capacity',$activity['capacity']??20) }}"></div>
<div><label for="status">Status</label><select class="form-select" id="status" name="status">@foreach($activity?['draft','open','full','ongoing','completed','cancelled','archived']:['draft','open'] as $status)<option @selected(old('status',$activity['status']??'draft')===$status)>{{ $status }}</option>@endforeach</select></div>
@if($role==='admin')<div><label for="coordinator_id">Assigned coordinator</label><select class="form-select" id="coordinator_id" name="coordinator_id" required>@foreach($coordinators as $c)<option value="{{ $c['user_id'] }}" @selected(old('coordinator_id',$activity['coordinator_id']??'')===$c['user_id'])>{{ $c['full_name'] }}</option>@endforeach</select></div>@endif
<div class="wide"><label for="requirements">Requirements / what to bring</label><textarea class="form-control" id="requirements" name="requirements" maxlength="2000">{{ old('requirements',$activity['requirements']??'') }}</textarea></div><div class="wide"><p>Cancel an activity to close its active enrollments. Complete or cancel it before archiving. Saved schedule or venue changes create a notice in live mode.</p><button class="btn btn-primary">Save activity</button></div></form>
@endsection
