@extends('layout')
@section('content')
<div class="heading"><div><p class="eyebrow">STAY ACTIVE. STAY CONNECTED.</p><h1>{{ $mine ? 'Your next chapter starts here.' : 'Good company. Great days ahead.' }}</h1><p class="intro">{{ $mine ? 'Keep track of the activities you have joined.' : 'Find something you love, learn something new, and enjoy it together.' }}</p></div></div>
@unless($mine)<section class="welcome-banner"><div><span class="mini-label">THERE’S A PLACE FOR YOU HERE</span><h2>A little movement.<br>A lot of connection.</h2><p>Make time for yourself and your community.<br>Explore activities at your own pace.</p><a href="#activities" class="btn btn-light">Find your next activity <span aria-hidden="true">↗</span></a></div><div class="banner-art" aria-hidden="true"><div class="sun"></div><div class="arch arch-one"></div><div class="arch arch-two"></div><div class="arch arch-three"></div><span class="art-caption">TOGETHER IS BETTER</span></div></section>@endunless
<section id="activities"><div class="section-heading"><div><h2>{{ $mine ? 'My activities' : 'Explore activities' }}</h2><p>{{ $mine ? 'Your confirmed places and waitlist requests, all in one place.' : 'Small moments. Meaningful connections.' }}</p></div><span class="result-count">{{ count($activities) }} {{ count($activities) === 1 ? 'activity' : 'activities' }}</span></div>
<form class="filters" method="get"><input type="hidden" name="mine" value="{{ $mine ? 1 : 0 }}"><div class="search-field"><label class="visually-hidden" for="search">Search activities or venues</label><input id="search" class="form-control" type="search" name="q" value="{{ $query }}" placeholder="Search activities or venues..."></div><label class="visually-hidden" for="category">Category</label><select class="form-select" id="category" name="category"><option value="">All categories</option>@foreach($categories as $c)@if($c['is_active'])<option @selected($category===$c['name'])>{{ $c['name'] }}</option>@endif @endforeach</select><label class="visually-hidden" for="activity-status">Activity status</label><select class="form-select" id="activity-status" name="status"><option value="">All statuses</option>@foreach(['open','full','ongoing','completed','cancelled'] as $state)<option value="{{ $state }}" @selected($status===$state)>{{ ucfirst($state) }}</option>@endforeach</select><button class="btn btn-primary">Find activities</button>@if($query || $category || $status)<a class="btn btn-outline-secondary" href="/?mine={{ $mine ? 1 : 0 }}">Clear</a>@endif</form>
<div class="activity-grid">@forelse($activities as $a)
@php($entry=collect($enrollments)->first(fn($e)=>$e['activity_id']===$a['activity_id'] && $e['status']!=='cancelled'))
<article class="activity-card"><div class="card-art {{ $a['art'] ?? 'garden' }}" aria-hidden="true"><span class="art-shape shape-one"></span><span class="art-shape shape-two"></span><span class="art-shape shape-three"></span><span class="art-word">{{ strtoupper($a['categories']['name'] ?? 'COMMUNITY') }}</span></div><div class="card-content"><div class="card-meta"><span class="category-pill">{{ $a['categories']['name'] ?? 'Community' }}</span>@if($entry)<span class="enrollment-state">{{ ucfirst($entry['status']) }}</span>@elseif(isset($a['confirmed']))<span class="availability">{{ $a['capacity']-$a['confirmed'] > 0 ? ($a['capacity']-$a['confirmed']).' spots left' : 'Waitlist available' }}</span>@else<span class="availability">{{ ucfirst($a['status']) }}</span>@endif</div><h3><a href="/activities/{{ $a['activity_id'] }}">{{ $a['title'] }}</a></h3><p class="schedule">{{ \Carbon\Carbon::parse($a['start_at'])->timezone(config('app.timezone'))->format('D, M j · g:i A') }}</p><p class="venue">{{ $a['venue'] }}</p><a class="card-action" href="/activities/{{ $a['activity_id'] }}">View activity <span aria-hidden="true">→</span></a></div></article>
@empty<div class="empty-state"><h3>{{ $mine ? 'Your calendar is ready for something good.' : 'No activities found.' }}</h3><p>{{ $mine ? 'Explore an activity and join when you are ready.' : 'Try another category or search term.' }}</p><a href="/" class="btn btn-primary">Explore all activities</a></div>@endforelse</div></section>
<div class="community-note"><span aria-hidden="true">✦</span><p><strong>Every connection counts.</strong> Choose an activity that feels right for you. We’re glad you’re here.</p></div>
@endsection

